[general]
description = "Experimental YAML 1.3 implementation in Ada"
licenses = ["MIT"]
authors = ["Felix Krause"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
website = "https://ada.yaml.io/"

    [general.gpr-externals]
    Mode = ["debug", "release"]

['0.3']
origin = "https://github.com/yaml/AdaYaml/archive/v0.3.0.tar.gz"
origin-hashes = ["sha512:ab19e38704e5d51a3f66da2fb9f86571ab08a6793a5d5f42ca29c3271bc754a1a845cc831d7fb24bb19c2caaf0d355ba250d0dca2959607a19936b0a91739d33"]
project-files = ["yaml.gpr", "yaml-utils.gpr", "yaml-annotation_processor.gpr", "yaml-server.gpr"]
executables = ["yaml-server"]

    ['0.3'.depends-on]
    simple_components = "^4.27"

['0.2']
origin = "https://github.com/yaml/AdaYaml/archive/v0.2.0.tar.gz"
origin-hashes = ["sha512:b9722c24ef5f4d08973890116603fce68ad00c7a96e2cab01c7cbb6f537068877257fff5fd325efc8d29f236be4f8546ae8e75619a7a77563d339bd159d9e20b"]
project-files = ["yaml.gpr", "yaml-utils.gpr"]
