[general]
description = "Library implementing the deflate method from gzip/PKZIP"
licenses = []
authors = ["Jean-loup Gailly", "Mark Adler"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

['1.2']

    ['1.2'.origin.'case(distribution)']
    'debian|ubuntu' = "native:zlib1g-dev"
    '...' = ""
