[general]
description = "Library implementing the deflate method from gzip/PKZIP"
licenses = []
authors = ["Jean-loup Gailly", "Mark Adler"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["zlib1g-dev"]
