[general]
description = "Ada Semantic Interface Specification or ASIS (library part)"
licenses = ["GPL 3.0"]
authors = ["AdaCore"]
website = "https://www.adacore.com/download/more"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

    [general.depends-on]
    make = "any"

[2018]
origin = "http://mirrors.cdn.adacore.com/art/5b0819e0c7a447df26c27ab8"
archive-name = "asis-gpl-2018-20180524-src.tar.gz"
origin-hashes= ["sha512:e00750adf17df8d534f0e561d129002d8b3c9efd6ba9c8d6768840d1399933271d748bafb7358a45d0a520620a335e669a6c2770ed89660bb319b609961a433a"]
project-files = ["asis.gpr"]

    [[2018.actions]]
    type = "post-fetch"
    command = "make setup-snames"

    [2018.available.'case(compiler)']
    gnat-community-2018 = true
    "..." = false

[2017]
origin = "http://mirrors.cdn.adacore.com/art/591c45e2c7a447af2deecffb"
archive-name = "asis-gpl-2017-src.tar.gz"
origin-hashes = ["sha512:dee6b8e0851a4b3181d50256697865f7a6a613eef7b59e43cb1a0b066e794d927db9f60df33f7e1af343d41801a6b66feb1f7a963523b2442c85ca506d7e112f"]
project-files = ["asis.gpr"]

    [[2017.actions]]
    type = "post-fetch"
    command = "make setup-snames"

    [2017.available.'case(compiler)']
    gnat-community-2018 = true
    "..." = false
