[general]
description = "Utility for directing compilation"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
licenses = []

[[external]]
kind = "output-version"
version-command = [ "make", "--version" ]
version-regexp = ".*Make ([\\d\\.]+).*"
