[general]
description = "Utility for directing compilation"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
licenses = []

[0]
origin = "native:make"
#    [0.origin.'case(distribution)']
#    'debian|ubuntu' = "native:make"
#    '...' = ""
