name = "gnat_linux64"
version = "10.3-1"
description = "The GNAT Ada compiler"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

provides = ["gnat=10.3-1"]

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"

# Native compiler
[origin."case(os)".linux."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-10.3.0-1/gnat-x86_64-linux-10.3.0-1.tar.gz"
hashes = ["sha256:8b7c5dcd858ba01bbb66053bcc2899a7015ef426b0f90d47b5b142b90886a6a2"]
