[general]
description = "GNAT Components Collection - Slim version (no dependencies)"
licenses = ["GPL 3.0"]
authors = ["AdaCore"]
maintainers = ["alejandro@mosteo.com"]

# This crate has a hidden conflict with any other gnatcoll.
# Declaring conflicts was removed during index transition 
# and it's still not reinstated.

project-files = ["gnatcoll.gpr"]

    [general.gpr-externals]
    GNATCOLL_ATOMICS = ["intrinsic", "mutex"]
    GNATCOLL_OS = ["windows", "unix", "osx"]
    BUILD = ["DEBUG", "PROD"]
    LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

    [general.gpr-set-externals]
    BUILD = "PROD"
    LIBRARY_TYPE = "static-pic"

        [general.gpr-set-externals.'case(os)']
        linux = { GNATCOLL_OS = "unix" }
        macos = { GNATCOLL_OS = "osx" }
        windows = { GNATCOLL_OS = "windows" }

[20180425]
origin = "git+https://github.com/alire-project/gnatcoll-core.git@7823e31add7133b9fbc6e037d9986a823e840dc0"

    [20180425.available.'case(compiler)']
    'gnat-community-2018' = true
    '...' = false
