[general]
description = "Ada binding to the ncurses text interface library"
authors = ["Thomas E. Dickey", "Juergen Pfeifer", "Eugene V Melaragno",
           "Nicolas Boulenguez"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
licenses = []

    [general.depends-on]
    gnat = "any"

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libncursesada6.1.20180127-dev",
                       "libncursesada5-dev",
                       "libncursesada3-dev"]
