[general]
description = "GNAT is a compiler for the Ada programming language"
licenses = []
maintainers = ["alejandro@mosteo.com"]

# Until we rework the native package situation, the intention here is to
# depend on the native compiler, and not in a particular version. Hence,
# although versions do not match here, we get the intended result.

[0]
    [0.origin.'case(distribution)']
    'debian|ubuntu' = "native:gnat"
    '...' = ""
