[general]
description = "GNAT Components Collection - Core packages"
licenses = ["GPL 3.0"]
authors = ["AdaCore"]
maintainers = ["alejandro@mosteo.com"]

    [general.gpr-externals]
    GNATCOLL_ATOMICS = ["intrinsic", "mutex"]
    GNATCOLL_OS = ["windows", "unix", "osx"]
    BUILD = ["DEBUG", "PROD"]
    LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

    [general.gpr-set-externals]
    BUILD = "PROD"
    LIBRARY_TYPE = "static-pic"

        [general.gpr-set-externals.'case(os)']
        linux = { GNATCOLL_OS = "unix" }
        macos = { GNATCOLL_OS = "osx" }
        windows = { GNATCOLL_OS = "windows" }

[2018]
origin = "http://mirrors.cdn.adacore.com/art/5b0819dfc7a447df26c27a99"
archive-name = "gnatcoll-core-gpl-2018-20180524-src.tar.gz"
archive-hash = "sha512:bf6082573dc537836ea8506a2c9a75dc7837440c35c5b02a52add52e38290d99e90a9706690591f8899b8b4935824b195f230b3aa1c4da10911e3caf954c04ac"
project-files = ["gnatcoll-core-gpl-2018-src/gnatcoll.gpr"]

    [2018.available.'case(compiler)']
    'gnat-community-2018' = true
    '...' = false
