[general]
description = "GNAT is a compiler for the Ada programming language"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "version-output"
version-command = [ "gnat", "--version" ]
version-regexp = "^GNAT ([\\d\\.]+).*|^GNAT Community ([\\d]{4}).*"
