[general]
description = "Open Database Connectivity drivers for UNIX platforms"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
website = "http://www.unixodbc.org"

[[external]]
kind = "system"
origin = ["unixodbc-dev"]
