[general]
description = "Open Database Connectivity drivers for UNIX platforms"
licenses = []
maintainers = ["alejandro@mosteo.com"]
website = "http://www.unixodbc.org"

['2.3']
    ['2.3'.origin.'case(distribution)']
    'debian|ubuntu' = "native:unixodbc-dev"
    '...' = ""
