[general]
description = "A crypto library for Ada with a nice API"
licenses = ["GMGPL 2.0", "GMGPL 3.0"]
authors = ["Christian Forler"]
maintainers = ["alejandro@mosteo.com"]

project-files = ["libadacrypt.gpr"]

    [general.available.'case(os)']
    linux = true
    windows = true

    [general.gpr-externals]
    system = ["unix", "windows"]
    mode = ["debug", "release"]

    [general.gpr-set-externals.'case(os)']
        linux = { system = "unix" }
        windows = { system = "windows" }

['0.8.7']
origin = "git+https://github.com/alire-project/Ada-Crypto-Library.git@33d15283abbc6d8a51d717de2bd822e026710c0d"
notes = "It fails self-tests; might be a spurious warning"
