name = "gprbuild"
version = "21.0.0"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

[environment."case(os)".linux]
PATH.append = "${CRATE_ROOT}/bin"

[origin."case(os)".linux."case(word-size)".bits-64]
url = "https://github.com/Fabien-Chouteau/verbose-fiesta/releases/download/plop/gprbuild-x86_64-linux-21.0.0.tar.gz"
hashes = ["sha512:94271fdbdda61eee19ac3877d5f7d4425230aec913332d90d8d53019585ef0b982f2bfe340270a6eb63f3605412be2d57900bc5c121f5edfafad7f4aa0173c6b"]
