[general]
description = "Multiprecision arithmetic library development files"
licenses = []
maintainers = ["derodat@adacore.com"]
maintainers-logins = ["pmderodat"]

[[external]]
kind = "system"
   [external.origin.'case(distribution)']
   'debian|ubuntu' = ["system:libgmp-dev"]
