[general]
description = "Drawing of ASCII graphs"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

['2.8.1-3']
    ['2.8.1-3'.origin.'case(distribution)']
    'debian|ubuntu' = "native:libgraph-easy-perl"
    '...' = ""
