[general]
description = "The GNU Scientific Library (GSL)"
licenses = []
maintainers = ["alejandro@mosteo.com"]

[0]
    [0.origin.'case(distribution)']
    'debian|ubuntu' = "native:libgsl-dev"
    '...' = ""
