[general]
description = "Simple DirectMedia Layer development files"
licenses = []
maintainers = ["alejandro@mosteo.com"]

[2]
    [2.origin.'case(distribution)']
    'debian|ubuntu' = "native:libsdl2-dev"
    '...' = ""
