[general]
description = "X11 client-side library"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[2]
    [2.origin.'case(distribution)']
    'debian|ubuntu' = "native:libx11-dev"
    '...' = ""
