[general]
description = "Thick Ada binding for OpenGL and GLFW"
licenses = ["MIT"]
authors = ["Felix Krause <contact@flyx.org>"]
website = "http://flyx.github.io/OpenGLAda/"
maintainers = ["Felix Krause <contact@flyx.org>"]
maintainers-logins = ["flyx"]

project-files = ["opengl.gpr", "opengl-glfw.gpr", "opengl-soil.gpr",
                 "opengl-test.gpr"]

executables = ["gl_test-opengl3", "gl_test-context", "gl_test-vbos",
               "gl_test-shaders", "gl_test-framebuffers",
               "gl_test-immediate"]

    [general.gpr-externals]
    GLFW_Version = ["2", "3"]
    Mode = ["debug", "release"]
    Auto_Exceptions = ["enabled", "disabled"]

    [general.gpr-set-externals.'case(os)']
    linux = { Windowing_System = "x11" }

['0.6']
origin = "https://github.com/flyx/OpenGLAda/archive/v0.6.tar.gz"
origin-hashes = ["sha512:764ed2caad37a9fb0897316724bfa53f53211b96fec63508c9926418a5cfc3e111b40b2352ad797a7ea855e269b4762d8de2306e747ef52b2eed71660e06a87c"]

    ['0.6'.depends-on.'case(os)'.linux]
    libglfw3 = "^3"
    libx11 = "^2"
