name = "gnat_macos64"
version = "10.3-1"
description = "The GNAT Ada compiler"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

provides = ["gnat=10.3-1"]

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

# Native compiler
[origin."case(os)".macos."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-10.3.0-1/gnat-x86_64-darwin-10.3.0-1.tar.gz"
hashes = ["sha256:20b3092f830adda081737e2d66322da8d4ad2bb9f5aa985bd18312d04fc61458"]
