[general]

description = "RxAda port of the Rx framework"
licenses = ["LGPL 3.0"]
authors = ["Alejandro R. Mosteo"]
maintainers = ["alejandro@mosteo.com"]

executables = ["rx-examples-basic", "rx-examples-minimal",
               "rx-examples-tests", "rx-examples-threading"]

project-files = ["rxada.gpr",
                 "rxada_lib.gpr", 
                 "rxada_examples.gpr"]

['0.1.0']
origin = "git+https://github.com/mosteo/rxada@918a9831b9c0ab7a478442040e06032b5218021a"
