[general]
description = "Ada Web Server"
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
licenses = []

[[external]]
kind = "hint"
hint = "Available through GNAT CE bundles"
available.'case(toolchain)'.system = false

[[external]]
kind = "system"
origin = ["libaws3.3.2.2-dev"]
available.'case(toolchain)'.user = false
