[general]
description = "Ada Web Server"
long-description = "This is a placeholder for an unsupported crate. Please contact the maintainer if you want to take over packaging and maintenance of this crate."
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
licenses = []
tags = ["server", "web"]

[[external]]
kind = "hint"
# Marked as unavailable external until it's properly packaged
