[general]
description = "Alex's Ada Assortment (of miscellaneous utilities)"
licenses = ["LGPL 3.0"]
authors = ["Alejandro R. Mosteo"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

['0.1']
origin = "https://github.com/mosteo/aaa/archive/v0.1.tar.gz"
origin-hashes = ["sha512:a9908afa198644d1b9965a7cbc3a9d39d887d1ddd1379dcda7c7b32ecc203de559dad01a5c0bc8c557ba449a343a4f0545669b725099db24014ab389eb586ff0"]
