name = "gnat_windows64"
version = "10.3-1"
description = "The GNAT Ada compiler"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

provides = ["gnat=10.3-1"]

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

# Native compiler
[origin."case(os)".windows."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-10.3.0-1/gnat-x86_64-windows64-10.3.0-1.tar.gz"
hashes = ["sha256:6d85b367c642195308440f5b8bdc10b529e2014d58c4ada06e9c8a1f86bf5342"]
