[general]
description = "OpenGL Utility Toolkit"
licenses = []
maintainers = ["alejandro@mosteo.com"]

['2.8.1-3']
    ['2.8.1-3'.origin.'case(distribution)']
    'debian|ubuntu' = "native:freeglut3-dev"
