name = "gnat_riscv64"
version = "10.3-1"
description = "The GNAT Ada compiler - RISC-V cross-compiler"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]

auto-gpr-with = false

provides = ["gnat=10.3-1"]

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/bin"

[origin."case(os)".linux."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-10.3.0-1/gnat-riscv64-elf-linux64-10.3.0-1.tar.gz"
hashes = ["sha256:209ee8df59c3f84412f9cb5121a2df4db45daedce47fbd19f7318461b1a4c00a"]
