[general]
description = "Ada binding for the GTK+ GUI"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
available.'case(toolchain)'.user = false
   [external.origin.'case(distribution)']
   'debian|ubuntu' = ["libgtkada16.1.0-dev"]
